name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  job_release:
    name: Create Release and Upload to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build
      id: build
      run: |
        python setup.py build sdist bdist_wheel

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          dist/*

    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        # repository_url: https://test.pypi.org/legacy/
        password: ${{ secrets.PYPI_TOKEN }}
        # skip_existing: true
        verbose: true
